version: 0.0
os: linux
files:
  - source: /
    destination: /usr/local/barnes/projects/barnes-collection-www
hooks:
  AfterInstall:
    - location: /ubuntu/post-deploy.sh
      timeout: 300
      runas: ubuntu
