// Static copyrights list
const copyrights = {
	'In Copyright': [1, 3],
	'Copyright Undetermined': [2, 6],
	'Public Domain': [4, 7, 8, 10],
};

// Static years list
const years = [
	'-4000',
	'1',
	'1000',
	'1500',
	'1600',
	'1700',
	'1800',
	'1810',
	'1820',
	'1830',
	'1840',
	'1850',
	'1860',
	'1870',
	'1880',
	'1890',
	'1900',
	'1905',
	'1910',
	'1915',
	'1920',
	'1930',
	'1940',
	'1950',
	'1960'
];

// Static cultures list
const cultures = [
	'Acoma Pueblo',
	'Akan',
	'Akye',
	'American',
	'Anyi',
	'Austrian',
	'Baluch',
	'Bamana',
	'Bamileke',
	'Baule',
	'Beembe',
	'Chinese',
	'Continental',
	'Cretan',
	'Cypriot',
	'Dan',
	'Dogon peoples',
	'Dutch',
	'Edo',
	'Egyptian',
	'English',
	'Etruscan',
	'European',
	'Fang',
	'Flemish',
	'French',
	'German',
	'Greek',
	'Guro',
	'Indian',
	'Iranian',
	'Italian',
	'Japanese',
	'Jula',
	'Kanyok',
	'Kissa',
	'Kongo',
	'Korean',
	'Kota',
	'Kuba',
	'Kulango',
	'Kyaman',
	'Lagoon',
	'Lega',
	'Luba',
	'Luluwa',
	'Mande',
	'Marka',
	'Merina',
	'Mesopotamian',
	'Mexican',
	'Middle Eastern',
	'Mossi',
	'Navajo',
	'Ndengese',
	'Netherlandish',
	'New Mexican',
	'Nsapo',
	'Oceanian',
	'Pende',
	'Persian',
	'Punu',
	'Roman',
	'San Ildefonso Pueblo',
	'Santa Ana Pueblo',
	'Santo Domingo Pueblo',
	'Sapi',
	'Scottish',
	'Senufo',
	'Sherbro',
	'Songye',
	'Spanish',
	'Sri Lankan',
	'Suku',
	'Syrian',
	'Swedish',
	'Teke',
	'Tesuque Pueblo',
	'Thai',
	'Tsogho',
	'Turkish',
	'Vili',
	'Yaka',
	'Zia Pueblo',
	'Zuni Pueblo',
	'Belorussian',
	'Icelandic',
	'Ukrainian',
	'Polish',
	'Swiss',
	'Norwegian',
	'Canadian',
	'Russian',
];

const culturesMap = {
	'Native American': [
		'Acoma Pueblo',
		'Acoma Pueblo/Laguna Pueblo',
		'Navajo',
		'Probably Zuni Pueblo',
		'San Ildefonso Pueblo',
		'Santa Ana Pueblo',
		'Santo Domingo Pueblo',
		'Tesuque Pueblo',
		'Zia Pueblo',
		'Zuni Pueblo',
	],
	'Asian': [
		'Central Indian',
		'Chinese',
		'Indian',
		'Indian (Andhra Pradesh?)',
		'Indian (Mathura)',
		'Japanese',
		'Korean',
		'Thai'
	],
	'African': [
		'Akan',
		'Bamana',
		'Bamana or Marka',
		'Bamileke',
		'Baule',
		'Beembe',
		'Benin Kingdom, Edo',
		'Bwende',
		'Dan',
		'Dogon peoples',
		'Edo',
		'Fang',
		'Fang Betsi',
		'Fang-Beti',
		'Guro',
		'Jula or Kulango',
		'Kanyok',
		'Kissi',
		'Kongo',
		'Kongo or Vili',
		'Kongo-Vili',
		'Kota',
		'Kota, Mbamba group',
		'Kota, Ndassa or Wumbu group',
		'Kuba',
		'Kuba or Ndengese',
		'Kuba, Shoowa',
		'Kyaman or Akye',
		'Lagoon',
		'Lagoon, Baule, or Anyi',
		'Lega',
		'Luba/Songye',
		'Luluwa',
		'Mande, possibly Malinké',
		'Merina',
		'Mossi',
		'Nsapo',
		'Pende, Central or Kwilu',
		'Possibly Suku',
		'Probably Luba',
		'Punu',
		'Senufo',
		'Southern Fang',
		'Suku or Hungaan',
		'Teke',
		'Tsogho',
		'Yaka',
	],
	'Latin American': [
		'Mexican',
		'Colonial Mexican',
	],
}

module.exports = {
	copyrights,
	years,
	cultures,
	culturesMap,
};
